### PR TITLE
SW-522 - Pull latest version of moveit

### PR DESCRIPTION
**Pull request by bhomberg**
### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [ ] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Include a screenshot if changing a GUI
- [ ] Optional: Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [ ] Optional: Decide if this should be cherry-picked to other current ROS branches (Indigo, Jade, Kinetic)

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by bhomberg** [comment]
Should go in at the same time as https://github.com/iron-ox/iron_ox/pull/921

**Comment by jonbinney** [comment]
@bhomberg This compiles fine for me, and i'm able to run reachability anlysis, but experience the same rviz problem you did: https://ironox.atlassian.net/browse/SW-580  I'm digging into that now; I'd like to at least understand the cause before we merge.

**Comment by bhomberg** [comment]
I don't think the moveit change caused the rviz issues -- I was seeing them just after running a rosdep update last week.  However, this PR will cause people to do a rosdep update, so I agree that we should figure the rviz thing out first.

**Review by jonbinney — APPROVED** [review]
Approved - the rviz issue appears unrelated to this, and we'll have to separately find a workaround.

**Pull request merged**
